CREATE TABLE IF NOT EXISTS materials (
  id SERIAL PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  tagline VARCHAR(200),
  description TEXT NOT NULL,
  temp_nozzle VARCHAR(50),
  temp_bed VARCHAR(50),
  heat_resistance VARCHAR(50),
  durability_score INT DEFAULT 3,
  flexibility_score INT DEFAULT 2,
  print_ease_score INT DEFAULT 5,
  finish_type VARCHAR(100),
  accent_color VARCHAR(50) DEFAULT '#00B8A9',
  benefits JSONB NOT NULL DEFAULT '[]',
  drawbacks JSONB NOT NULL DEFAULT '[]',
  ideal_for JSONB NOT NULL DEFAULT '[]',
  order_index INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed Initial Materials: PLA, PETG, ABS, ASA
INSERT INTO materials (
  code, name, tagline, description, temp_nozzle, temp_bed, heat_resistance,
  durability_score, flexibility_score, print_ease_score, finish_type, accent_color,
  benefits, drawbacks, ideal_for, order_index, is_active
) VALUES
(
  'pla',
  'PLA (Polylactic Acid)',
  'Everyday Precision & Clean Details',
  'Made from renewable resources like corn starch, PLA is our most popular filament for indoor lifestyle, desk accessories, and detailed display pieces. It delivers razor-sharp layer lines, smooth surfaces, and zero odor.',
  '190–220°C',
  '45–60°C',
  '55°C (Low)',
  3,
  2,
  5,
  'Clean, silky matte finish',
  '#00B8A9',
  '["Ultra-sharp print details and clean overhangs", "Eco-friendly, renewable plant-based bioplastic", "Vibrant, uniform matte & satin colors", "Minimal thermal warping & highly dimensionally accurate"]'::jsonb,
  '["Deforms in hot environments above 55°C (avoid hot cars)", "Rigid but can be brittle under severe shear impact"]'::jsonb,
  '["Desk accessories, organizers & phone docks", "Artistic planters, vases & decorative home decor", "Cosplay props, prototypes & architectural models"]'::jsonb,
  0,
  true
),
(
  'petg',
  'PETG (Polyethylene Terephthalate Glycol)',
  'Durable, Flexible & Moisture Resistant',
  'The gold standard for functional household, kitchen, and bathroom pieces. PETG combines the printing ease of PLA with the impact toughness and chemical resistance of ABS. Naturally moisture-resistant and shock-absorbing.',
  '230–250°C',
  '70–85°C',
  '75°C (Medium)',
  4,
  3,
  4,
  'Semi-glossy, smooth and impact-resistant',
  '#3B82F6',
  '["High impact resistance & tensile strength", "Impervious to water, soaps & household chemicals", "Exceptional layer adhesion and shatter resistance", "Safe for bathroom splash zones and kitchen utility"]'::jsonb,
  '["Slightly more prone to fine stringing than PLA", "Softer surface can scratch under abrasive metal contact"]'::jsonb,
  '["Bathroom accessories, soap trays & shower hooks", "Mechanical brackets, tool holders & snap-fits", "Everyday carry items, keychains & phone mounts"]'::jsonb,
  1,
  true
),
(
  'abs',
  'ABS (Acrylonitrile Butadiene Styrene)',
  'High-Strength & Heat-Tolerant Engineering',
  'The classic engineering polymer used in Lego bricks and automotive interiors. ABS handles high mechanical stress, impacts, and temperatures up to 100°C without softening. Can be post-processed and vapor smoothed.',
  '240–260°C',
  '95–110°C',
  '100°C (High)',
  5,
  3,
  3,
  'Matte, easily sandable & machinable',
  '#F59E0B',
  '["Exceptional drop and mechanical shock resistance", "Heat deflection up to 100°C (safe in hot vehicles)", "Can be acetone vapor-smoothed for a glass-like finish", "Lightweight with high ductility and machinability"]'::jsonb,
  '["Prone to thermal shrinkage and warping without an enclosure", "Mild styrene fumes during printing requiring filtration"]'::jsonb,
  '["Automotive interior mounts & glovebox brackets", "Enclosures for electronics and heated devices", "Heavy-use tools, functional gears & handles"]'::jsonb,
  2,
  true
),
(
  'asa',
  'ASA (Acrylonitrile Styrene Acrylate)',
  'The Ultimate Outdoor & UV Defender',
  'Engineered specifically to solve sunlight degradation. ASA retains all the high impact and thermal resistance of ABS while adding extreme UV resistance and weatherproofing that will never yellow, chalk, or crack outdoors.',
  '245–265°C',
  '95–110°C',
  '105°C (Extreme)',
  5,
  3,
  3,
  'Deep anti-glare matte texture',
  '#EC4899',
  '["Complete UV & sunlight resistance (zero fading or yellowing)", "Handles intense rain, frost, and outdoor heat up to 105°C", "High impact, tensile, and chemical resistance", "Premium anti-glare matte surface finish"]'::jsonb,
  '["Demands elevated chamber and bed temperatures", "Requires enclosed printing for large dimensional stability"]'::jsonb,
  '["Outdoor garden mounts, weather stations & solar brackets", "Exterior car, boat & motorcycle accessories", "Drone chassis, camera housings & outdoor utility fixtures"]'::jsonb,
  3,
  true
)
ON CONFLICT (code) DO NOTHING;
